### ISSUE TITLE
error on check lm sensor --list

### ISSUE THREAD

**Issue by BrixSat** [matteocorti/check_lm_sensors#15]
./check_lm_sensors --list
found temperature for drive sda Temp (sda Temp = 23)
found temperature for drive sda Temp (sda Temp = 23)
Use of uninitialized value $name in pattern match (m//) at ./check_lm_sensors line 325, <$IN> line 10.
Use of uninitialized value $name in concatenation (.) or string at ./check_lm_sensors line 329, <$IN> line 10.
Use of uninitialized value $name in concatenation (.) or string at ./check_lm_sensors line 331, <$IN> line 10.
Use of uninitialized value $name in concatenation (.) or string at ./check_lm_sensors line 365, <$output> line 1.
LM_SENSORS UNKNOWN - Error while executing /usr/sbin/hddtemp -n /dev/:

**Comment by BrixSat** [comment]
diff -Naur check_lm_sensors_fixed check_lm_sensors_with_error
```
--- check_lm_sensors	2020-01-10 15:21:25.623791678 +0000
+++ check_lm_sensors2	2020-01-10 15:22:20.709430891 +0000
@@ -322,10 +322,6 @@
                 next;
             }
 
-	    if ( not defined $name  ) {
-		next;
-	    }
-
             if ( $name =~ /[0-9]$/mx ) {
                 next;
             }
```

**Comment by matteocorti** [comment]
Thanks, I applied the fix. I do not have any HW machine on which I can test. If you are willing to help  to maintain the package let me know.

**Comment by BrixSat** [comment]
Sure, what can i do to help you?

**Comment by matteocorti** [comment]
If it's OK I'll give you write permission to the repository so that you can manage it

**Comment by BrixSat** [comment]
Sure :)
